#!/bin/bash

#SBATCH --job-name=alexEvent
#SBATCH -p gpu
#SBATCH -A amowli_lab_gpu
#SBATCH -N 1
#SBATCH -n 8
#SBATCH --error=slurm-%J.err
#SBATCH -t 01-00:00:00
#SBATCH --gres=gpu:A30:1
#SBATCH --mail-type=end
#SBATCH --mail-user=sarani@uci.edu

module load pytorch/1.11.0

conda activate event-data-utility-functions

#python3 basicSNN.py
#python3 snnTry.py
#python3 lstmTry.py
#python3 convNextNetEvent.py
#python3 alexNetEvent.py
python3 modelTester.py
